{
 "title": "DRF Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency GET /hello",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{method=\"GET\",view=\"hello\"}[5m]))\n    by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP GET Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}